sudo: required
language: go
go: master

services:
  - docker

before_install:
  - ./prereq.sh
  - go test

after_success:
  - ./test.sh
  - if [ "$TRAVIS_BRANCH" == "master" ]
  - then
  - ./build.sh
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
  - docker push antihax/eve-axiom
  - fi
  